### ISSUE TITLE
"none of the screenshots were copied" issue

### ISSUE THREAD

**Issue by TearsofCyanide** [awthwathje/SteaScree#21]
I am unsure if this is still active or being worked on however I seem to be having an issue copying the screenshot I select to the selected directory. I have been following the instructions as found; but no matter what I cannot seem to get it to work as every time a red text appears saying "None of the screenshots were copied" and then everything in the box is unclickable; meaning I have to restart the app just to try again. 
I feel like I am simply overlooking something but all the same I may need some elaboration and small details on how to make this work correctly.
Thanks in advance.

**Comment by awthwathje** [comment]
Hey, yes, this tool is maintained and reported bugs are welcome. I'm not sure why you closed this issue, did you manage to resolve it yourself?

**Comment by TearsofCyanide** [comment]
Yes; I managed to figure out that the application needed PNG images and not JPG images like I thought before. I don't remember reading anything bout what format the application needed; thus my confusion. If it isn't noted anywhere it may help to put it on thw download page; if it was already there then I must have overlooked it. 
Thanks again; and great job on the application.

**Comment by awthwathje** [comment]
Well, app should work properly with JPGs, PNGs, BMPs and TIFFs. In fact, if it receives JPGs it just uses them as is, and if the format is different, it automatically converts them to JPG. 

In your particular case, it seems to me that something went wrong with plain copy (and possible resize, if the source file was huge) and this problem was not present, when the app went by the conversion route.

This is probably a bug, and if you have some time, we can try to figure out what went wrong on your particular system. But in this case I'll need some cooperation from you, that is I'll periodically send test builds to you, expecting that you will use them and send logs back to me.
