### ISSUE TITLE
Portable build

### ISSUE THREAD

**Issue by damajor** [awthwathje/SteaScree#24]
Hi there,

It would be great to have a portable build of SteaScree.

**Comment by awthwathje** [comment]
Hi, sorry for the late answer, I missed the notification somehow.

macOS and Linux versions are already portable builds, but I'm not sure it's an easy thing to do for Windows. So I'd say that I could look into this in the future, but definitely not very soon since I'm busy these days.

Any help would be greatly appreciated.

**Comment by awthwathje** [comment]
I will prepare a portable build with the next minor release.

**Comment by awthwathje** [comment]
Good news, I prepared a portable build even before the next minor release. It's now downloadable from the official site.
