### ISSUE TITLE
Certain screens fail to upload to the Steam Cloud

### ISSUE THREAD

**Issue by lun3m** [awthwathje/SteaScree#9]
Hi, I noticed that for some reason some of my screens failed to upload to the Steam Cloud (no clue what I took them with anymore, think it was a game specific screenshot feature - happened to me only with one game). But I also managed to fix that: I converted them to jpeg for web with 100 % quality and exif+icc checked, and it fixed it (they were small jpegs to begin with). I'm adding the [faulty screens ](https://ufile.io/884df)_(hope it's ok here to send files this way)_ if you may wanna try to look into what causes it. 

Also, great software, thanks for making it.

**Comment by awthwathje** [comment]
Hey. Thanks for reporting, I'll take a look what goes wrong with these screenshots.

**Comment by awthwathje** [comment]
Found the issue with your non-uploadable JPEGs, they all encoded with _baseline_ [DCT](https://en.wikipedia.org/wiki/JPEG#Discrete_cosine_transform). For some reason, Steam doesn't like this encoding process. If you convert the file in question to _progressive_ DCT, e.g. like this:

`jpegtran -progressive 20170129020736_1.jpg > 20170129020736_1_progressive.jpg`

the file will be perfectly uploadable.

Historically, SteaScree doesn't modify original JPEGs, if they conform to Steam's size limits. However, because of this issue, it became clear, that all incoming JPEGs should be inspected before the uploading preparation.

I'll look how this DCT issue can be mitigated using Qt and will update SteaScree when the fix will be implemented. Hopefully next week.

**Comment by awthwathje** [comment]
The issue is fixed, now every incoming JPEG is checked whether it's baseline or progressive, and in the case of former, the whole image is processed and saved by Qt, just as it's done for PNGs and TIFFs. Progressive JPEGs are still copied as is.
